## your sample table, which must be a tab delimeted
## for detail, please look at the example files located in this directory
samples: config/samples.tsv

## threads
threads: 10

## your surro-seq library reference
ref: references/ref_small.fa

MergeByOverlap:
  ## flash params that control minimum length of overlap bewteen paired reads.
  min_overlap: 10

ExtractReads:
  ## use leftStart and leftEnd to control the location of scaffold in each library seq.
  leftStart: 15
  leftEnd: 118
  ## trap length maybe 37 or 27 if 10 bp barcodes were used in your library
  trapLength: 37

RemoveSyntheticErrors:
  ## use start and end to control the locations of reference seq as a template to remove
  ## sequences in control that are not same with
  ## must concordant with previous set
  start: 119
  end: 155

RealignToTrap:
  ## basically similar with RemoveSyntheticErrors
  start: 119
  end: 155

CreateIndelCountFile:
  ## remove short indels that happend out of core regions
  ## use the four params to control that areas.
  leftStart: 1
  leftEnd: 25
  rightStart: 32
  rightEnd: 37


